title: "GIS Portfolio"
description: "Spatial Analysis · Web Mapping · Remote Sensing · Cartography"
author: "Matthew Price"
email: "M.r.Price650@gmail.com"
github: "MPrice650"
linkedin: "matthew-price-83035291"
baseurl: ""
url: "https://MPrice650.github.io"

# Build settings
markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
